services:
    dns:
        container_name: dns
        volumes:
            - dns:/etc/bind
            - /etc/bind/named.conf.local:/etc/bind/named.conf.local
            - /var/lib/bind:/var/lib/bind
        network_mode: host
        restart: unless-stopped
        image: dns
volumes:
    dns:
        name: dns
